name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # allows pushing to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Emacs
        run: sudo apt-get install -y emacs-nox

      - name: Tangle and export Org site
        run: emacs --batch -l org --eval "(progn (find-file \"README.org\") (org-babel-tangle) (kill-emacs))"

      - name: Deploy site to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
